[package]
name = "ted"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[dependencies]
bincode = "0.3.0"
rustc-serialize = "0.3.*"
termion = "*"
clap = { version = "1.4.0", features = ["yaml"] }
time = "*"
